webapp/test/OPA5Tests.html
- Changed QUnit startup, such that it gets started as soon as the app is ready.
=> SAMPLE-APP: Changed QUnit opa5 tests startup

.travis.yml
- Use container-based images by specifying "sudo: false"
- Cache npm directory
- Use correct branch for "deploy" steps
=> Adopt .travis.yml

webapp/controller/App.controller.js, webapp/test/integration/AllJourneys.js, webapp/test/integration/FilterJourney.js, webapp/test/integration/pages/App.js, webapp/view/App.view.xml
=> Add tabs to filter items

webapp/css/styles.css, webapp/index.html, webapp/manifest.json, webapp/test/unit/controller/App.controller.js, webapp/view/App.view.xml
* Added Component ID
* Added async root view loading
* Improved styling of custom list item
=> Added new best practices for manifest and component

karma-ci.conf.js, karma.conf.js
Fixes https://github.com/SAP/openui5-sample-app/issues/34
=> [FIX] karma: include *.js files in the preprocessors

karma-ci.conf.js, package.json
* replaced phantom js with headless chrome
* updated dev dependencies (removed phantom js and updated karma version)
=> feature: replaced phantom js with headless chrome

karma.conf.js, package.json, webapp/Component.js, webapp/controller/App.controller.js, webapp/index-self-contained.html, webapp/index.html, webapp/manifest.json, webapp/test/integration/AllJourneys.js, webapp/test/integration/FilterJourney.js, webapp/test/integration/SearchJourney.js, webapp/test/integration/TodoListJourney.js, webapp/test/integration/arrangements/Startup.js, webapp/test/integration/opaTests.qunit.html, webapp/test/integration/opaTests.qunit.js, webapp/test/integration/pages/App.js, webapp/test/testsuite.qunit.html, webapp/test/testsuite.qunit.js, webapp/test/unit/AllTests.js, webapp/test/unit/allTests.js, webapp/test/unit/controller/App.controller.js, webapp/test/unit/unitTests.qunit.html, webapp/test/unit/unitTests.qunit.js, webapp/view/App.view.xml
* CSP Compliant entry points
* Declarative Component usage
* Updated OPA & Unit test setup
* Removed jQuery
* Added . in view events
* Minor cosmetic code cleanup
=> Update TODO app to latest UI5 recommendations

.gitignore, .npmrc, README.md, package-lock.json, package.json, webapp/css/styles.css, webapp/index.html, webapp/test/integration/opaTests.qunit.html, webapp/test/unit/unitTests.qunit.html
- Update UI5 dependencies
- Switch to SAP Quartz Light theme (sap_fiori_3)
- Add "local-web-server" to run a server on build results
- Fix CSS issue
=> Update to latest best practices / fix issues

package-lock.json, package.json, ui5.yaml
Depends on UI5 Tooling 2.0 release
Also see https://sap.github.io/ui5-tooling/
=> Adapt to UI5 Tooling 2.0

package.json
=> package.json: Use tabs instead of spaces

webapp/util/Helper.js, webapp/view/App.view.xml
Detected during karma execution where the HTML file is not in the app root
=> Fix img loading by using path relative to app namespace

CONTRIBUTING.md
=> [INTERNAL] Fixes typo

webapp/test/integration/AllJourneys.js, webapp/test/integration/SearchJourney.js, webapp/test/integration/pages/App.js, webapp/view/App.view.xml
Fixes: https://github.com/SAP/openui5-sample-app/issues/150
=> [INTERNAL] Fix integration tests on mobile devices

.github/workflows/github-ci.yml, package-lock.json, package.json
Update UI5 Tooling and karma-ui5 to v3
=> [DEPENDENCY] Update @ui5/cli and karma-ui5 to v3

.gitignore, package-lock.json, package.json, ui5.yaml, webapp/test/unit/unitTests.qunit.html
Enables UI5 Code Coverage middleware to instrument ES6+ code.
=> [FEATURE] Enable ui5 tooling middleware @ui5/middleware-code-coverage

README.md
JIRA: CPOUI5FOUNDATION-636
Updates documentation's link/unlink section with the new Workspaces concept.
=> [INTERNAL] Update documentation with workspaces

.github/workflows/deploy.yml, README.md
=> [FEATURE] add live demo

webapp/test/integration/opaTests.qunit.html
Enable client-side code coverage also for OPA5 tests.
=> [INTERNAL] Enable client-side code coverage also for OPA5 tests

package-lock.json, package.json
Demonstrates usage of UI5 linter.
=> [DEMO] Add UI5 linter

.eslintrc.json
=> ESLint: Use ES2023

package-lock.json, package.json, ui5.yaml, webapp/Component.js, webapp/manifest.json
=> [INTERNAL] Apply best practices after UI5 Tooling v4 upgrade

webapp/index.html
Resolves UI5 linter v1.0 warnings
=> [INTERNAL] index.html: Fix bootstrap tag names

webapp/test/Test.qunit.html, webapp/test/integration/FilterJourney.js, webapp/test/integration/SearchJourney.js, webapp/test/integration/TodoListJourney.js, webapp/test/integration/opaTests.qunit.js, webapp/test/testsuite.qunit.html, webapp/test/testsuite.qunit.js
Alignment with current best practices (e.g. in Testing Tutorial)
- Remove usage of `<base>` tag
- Usage of ui5:// protocol instead of relative page path
- Fix coverage exclusion for test modules
=> [INTERNAL] Update test setup

renovate.json
- Set `schedule` manually instead of default value
- Add commit message prefix
=> ci(renovate): Adjust lock file maintenance config

renovate.json
Align with existing commit message used for lock file updates.
=> ci(renovate): Adjust commit message for lock file updates

.github/workflows/deploy.yml, .github/workflows/github-ci.yml, .github/workflows/reuse-compliance.yml
Declares only the required permissions per workflow.
=> ci: Use least privilege principle for permissions
